# Conexión al Master de Spark
spark.master                     spark://spark-master:7077

# HDFS como sistema de archivos por defecto
spark.hadoop.fs.defaultFS        hdfs://namenode:9000

# Memoria para el Driver (proceso que coordina el job)
spark.driver.memory              512m

# Memoria para cada Executor (proceso que ejecuta las tareas)
spark.executor.memory            512m

# Número de cores por executor
spark.executor.cores             1

# Nivel de log (INFO, WARN, ERROR)
spark.eventLog.enabled           false